{% set name = "locopy" %}
{% set version = "0.6.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e44e19ae9b0bb8c4689138f875e116f3ea06142a5d58b7f8479faee4e0505fba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3 <=1.38.26,>=1.9.92
    - PyYAML <=6.0.2,>=5.1
    - pandas <=2.2.3,>=0.25.2
    - numpy <=2.2.6,>=1.22.0
    - polars >=0.20.0
    - pyarrow >=10.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - locopy

about:
  home: https://github.com/capitalone/locopy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Loading/Unloading to Redshift and Snowflake using Python
  doc_url: https://capitalone.github.io/locopy
  dev_url: https://github.com/capitalone/locopy

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
