{% set name = "locopy" %}
{% set version = "0.7.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 451305ead146dd57badd289258a41f694a02908bc1dd99e34b9a87766ade2c26

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3 <=1.42.34,>=1.9.92
    - PyYAML <=6.0.2,>=5.1
    - pandas <=2.3.3,>=0.25.2
    - numpy <=2.2.6,>=1.22.0
    - polars >=0.20.0
    - pyarrow >=10.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - locopy

about:
  home: https://github.com/capitalone/locopy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Loading/Unloading to Redshift and Snowflake using Python
  doc_url: https://capitalone.github.io/locopy
  dev_url: https://github.com/capitalone/locopy

extra:
  recipe-maintainers:
    - rhaffar
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
