{% set name = "locopy" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf3e74a061f9b66cb365782a5e20fbde179a290892df28d04120449388b6a567

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3 <=1.28.72,>=1.9.92
    - PyYAML <=6.0.1,>=5.1
    - pandas <=2.1.2,>=0.25.2
    - numpy <=1.26.1,>=1.22.0

test:
  imports:
    - locopy

about:
  home: https://github.com/capitalone/locopy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Loading/Unloading to Redshift and Snowflake using Python
  doc_url: https://capitalone.github.io/locopy
  dev_url: https://github.com/capitalone/locopy

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
    - NikhilJArora
