{% set name = "locopy" %}
{% set version = "0.6.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32dbe368ba71cd3a8d14f13119f603b2b41fcab31c6e56141ce36951d1d27fbf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3 <=1.37.17,>=1.9.92
    - PyYAML <=6.0.2,>=5.1
    - pandas <=2.2.3,>=0.25.2
    - numpy <=2.2.4,>=1.22.0
    - polars >=0.20.0
    - pyarrow >=10.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - locopy

about:
  home: https://github.com/capitalone/locopy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Loading/Unloading to Redshift and Snowflake using Python
  doc_url: https://capitalone.github.io/locopy
  dev_url: https://github.com/capitalone/locopy

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
