{% set name = "locopy" %}
{% set version = "0.6.6" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2876463c240c35a0804b222bb0832293cc996c470fbdf9110c3adf7a47e90dd7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3 <=1.40.0,>=1.9.92
    - PyYAML <=6.0.2,>=5.1
    - pandas <=2.3.1,>=0.25.2
    - numpy <=2.2.6,>=1.22.0
    - polars >=0.20.0
    - pyarrow >=10.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - locopy

about:
  home: https://github.com/capitalone/locopy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Loading/Unloading to Redshift and Snowflake using Python
  doc_url: https://capitalone.github.io/locopy
  dev_url: https://github.com/capitalone/locopy

extra:
  recipe-maintainers:
    - rhaffar
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
