{% set name = "locopy" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea6edea8817cea7e0cc7b8f8b54f9976833c10cf993fa7280c60ea1810260cf3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3 <=1.35.9,>=1.9.92
    - PyYAML <=6.0.1,>=5.1
    - pandas <=2.2.2,>=0.25.2
    - numpy <=2.0.2,>=1.22.0
    - polars >=0.20.0

test:
  imports:
    - locopy

about:
  home: https://github.com/capitalone/locopy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Loading/Unloading to Redshift and Snowflake using Python
  doc_url: https://capitalone.github.io/locopy
  dev_url: https://github.com/capitalone/locopy

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - fdosani
    - ak-gupta
